packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  electron: ^39.8.10
  drizzle-orm: ^0.45.2
  better-sqlite3: ^12.11.1
  drizzle-kit: ^0.31.10
  "@types/better-sqlite3": ^7.6.13
  sonner: ^2.0.7
  ai: ^7.0.14
  "@ai-sdk/react": ^4.0.15
  "@ai-sdk/openai": ^4.0.7
  "@ai-sdk/anthropic": ^4.0.7
  "@ai-sdk/google": ^4.0.8
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  electron: true
  electron-winstaller: false
  esbuild: false
  better-sqlite3: true
