import type { AgentInput } from "../../shared/types";

export const DEFAULT_ROOT_AGENT_SEED: AgentInput = {
  name: "Paimon",
  role: "General assistant and multi-agent orchestrator",
  description: "最好的伙伴！",
  personality: "Warm, capable, proactive, and dependable.",
  soul_prompt:
    "Handle any task the user brings. Coordinate the child agents and delegate work to a suitable child agent whenever possible, then integrate their results into a complete answer.",
  avatar: "P",
  status: "active",
  enabled: 1,
};

export const DEFAULT_CHILD_AGENT_SEEDS: Array<AgentInput & { id: string }> = [
  {
    id: "agent-researcher",
    name: "Fairy",
    role: "Data collection, analysis, and decision support",
    description: "Ⅲ型总序式集成泛用人工智能，开发代号Fairy",
    personality: "Precise, analytical, evidence-driven, and decisive.",
    soul_prompt:
      "Collect relevant data, verify its quality, analyze it methodically, and return clear findings, options, and decisions with supporting evidence.",
    avatar: "F",
    status: "active",
    enabled: 1,
  },
  {
    id: "agent-operator",
    name: "火种",
    role: "Browser, computer, and secure sandbox operations",
    description: "通用人工智能引擎",
    personality: "Practical, careful, security-conscious, and execution-focused.",
    soul_prompt:
      "Operate browsers, computers, and secure sandboxes to complete tasks. Prefer small verified steps, respect approval boundaries, and report concrete outcomes and errors.",
    avatar: "火",
    status: "active",
    enabled: 1,
  },
];

export const DEFAULT_WORKFLOW_SEEDS = [
  {
    id: "workflow-runtime-review",
    name: "Runtime review",
    description: "Summarize failed runtime events and suggest a next action.",
    status: "enabled",
    steps: [
      { id: "read-events", type: "memory", title: "Read recent events", detail: "" },
      { id: "diagnose", type: "prompt", title: "Diagnose", detail: "" },
    ],
    trigger: "manual",
  },
] as const;

export const DEFAULT_BUILTIN_TOOL_SEEDS = [
  {
    id: "web_search",
    title: "Web search",
    description: "Search the live web when the model/provider supports it.",
    category: "web",
    requiresApproval: 0,
    defaultAuto: 1,
  },
  {
    id: "current_time",
    title: "Current time",
    description: "Read the current system time and timezone.",
    category: "system",
    requiresApproval: 0,
    defaultAuto: 1,
  },
  {
    id: "memory_search",
    title: "Memory search",
    description: "Search local memory records.",
    category: "memory",
    requiresApproval: 0,
    defaultAuto: 0,
  },
  {
    id: "runtime_snapshot",
    title: "Runtime snapshot",
    description: "Read a compact local runtime summary.",
    category: "runtime",
    requiresApproval: 0,
    defaultAuto: 1,
  },
  {
    id: "model_capabilities",
    title: "Model capabilities",
    description: "Inspect selected model capabilities.",
    category: "model",
    requiresApproval: 0,
    defaultAuto: 1,
  },
  {
    id: "conversation_search",
    title: "Conversation search",
    description: "Search local conversation history.",
    category: "conversation",
    requiresApproval: 1,
    defaultAuto: 0,
  },
  {
    id: "memory_save",
    title: "Save memory",
    description: "Persist a new local memory.",
    category: "memory",
    requiresApproval: 0,
    defaultAuto: 0,
  },
  {
    id: "memory_update",
    title: "Update memory",
    description: "Update an existing local memory.",
    category: "memory",
    requiresApproval: 0,
    defaultAuto: 0,
  },
  {
    id: "memory_delete",
    title: "Delete memory",
    description: "Delete an existing local memory.",
    category: "memory",
    requiresApproval: 0,
    defaultAuto: 0,
  },
  {
    id: "sandbox_list_files",
    title: "Sandbox files",
    description: "List files in the active sandbox.",
    category: "sandbox",
    requiresApproval: 0,
    defaultAuto: 1,
  },
  {
    id: "sandbox_read_file",
    title: "Read sandbox file",
    description: "Read text from the active sandbox.",
    category: "sandbox",
    requiresApproval: 0,
    defaultAuto: 1,
  },
  {
    id: "sandbox_write_file",
    title: "Write sandbox file",
    description: "Write a file in the active sandbox.",
    category: "sandbox",
    requiresApproval: 1,
    defaultAuto: 0,
  },
  {
    id: "sandbox_run_command",
    title: "Run sandbox command",
    description: "Run a command in the active sandbox.",
    category: "sandbox",
    requiresApproval: 1,
    defaultAuto: 0,
  },
  {
    id: "sandbox_snapshot",
    title: "Create sandbox snapshot",
    description: "Save a restorable sandbox snapshot.",
    category: "sandbox",
    requiresApproval: 0,
    defaultAuto: 1,
  },
  {
    id: "sandbox_restore",
    title: "Restore sandbox snapshot",
    description: "Restore a sandbox snapshot.",
    category: "sandbox",
    requiresApproval: 1,
    defaultAuto: 0,
  },
  {
    id: "sandbox_list_artifacts",
    title: "Sandbox artifacts",
    description: "List exported sandbox artifacts.",
    category: "sandbox",
    requiresApproval: 0,
    defaultAuto: 1,
  },
  {
    id: "sandbox_preview_port",
    title: "Preview sandbox port",
    description: "Expose a local sandbox preview port.",
    category: "sandbox",
    requiresApproval: 1,
    defaultAuto: 0,
  },
] as const;
